const UrlConstants = {
  //  BASE_URL:'https://reqres.in/api/users?page=2',
  // BASE_URL: 'https://faaziqa123.loca.lt/doctor-mobile/',
  // BASE_URL: 'http://34.93.130.230:8080/doctor-mobile/',
  // BASE_URL: 'http://34.93.224.0:8080/mobile/',
  BASE_URL: 'https://runpasw.shop/mobile/',
  LOGIN: 'user/login',
  TEST_API:'user/testapi',
  GET_MY_PROFILE:'user/getMyProfile',
  FORGOT_PASSWORD:'',
  ADD_CATEGORY:'category/addCategory',
  GET_ALL_CATEGORY:'category/getAllCategory',
  GET_ALL_BRAND:'brand/getAllBrand',
  GET_ALL_SUB_CATEGORY:'subCategory/getallSubCategories',
  GET_ALL_SUB_CATEGORY_BY_CATEGORY_IDE: 'subCategory/getallSubCategoriesByCategoryPK/',
  DELETE_CATEGORIE:'category/deleteCategory/',
  UPDATE_CATEGORIE:'category/updateCategory/',
  UPDATE_SUB_CATEGORIE:'subCategory/updateSubCategory/',
  UPDATE_BRAND: 'brand/updateBrand/',
  UPDATE_MODAL_NUMBER: 'ProductModalNumber/updateModelNumber/',
  UPDATE_COLOR: 'color/updateColorName',
  UPDATE_VARIANT: 'variant/updateVariant',
  DELETE_VARIANT: 'variant/deleteVariantById',
  UPDATE_PRODUCT_PART_LABEL: 'ProductPart/updateProductPart',
  UPDATE_REPAIR_COST: 'RepairCost/update',
  UPDATE_INVENTORY: 'inventory/updateInventory',
  UPDATE_SUPPORT_TICKET: 'supportTicket/update',
  UPDATE_ORDER: 'unitRepair/updateUnitRepairOrderPriceOrDescriptionOrStatusByManager',

  GET_ALL_PRODUCT_PART_LABEL: 'ProductPart/getAllProductPart',
  GET_PRODUCT_PART_LABEL_BY_SUB_CATEGORY_ID: 'ProductPart/getPartItemBySubCategoryId',
  ADD_PRODUCT_PART_LABEL: 'ProductPart/createProductPart',
  GET_ALL_REPAIR_COST: 'RepairCost/getAllRepairCost',
  GET_REPAIR_COST_BY_ID: 'RepairCost/getAllRepairCostByModelNumber', 
  GET_REPAIR_COST_BY_SUBCATEGORY_ID: 'RepairCost/getAllRepairCostBySubCategoryId',
ADD_REPAIR_COST_: 'RepairCost/add',  
GET_ALL_INVENTORY: 'inventory/getAllInventory',
ADD_INVENTORY: 'inventory/create',
GET_ALL_REPAIR_UNIT_ORDER_BY_USER_ID: 'unitRepair/getAllUnitRepairOrderByFilter',
ADD_RE_FILL_INVENTORY: 'inventory/reFillInventory',
GET_INVENTORY_HISTORY: 'inventoryUsageHistory/getInventoryHistoryByInventoryId',
ORDER_INVENTORY_USE: 'inventory/consumeInventoryItem',
GET_ALL_SUPPORT_TICKET: 'supportTicket/getAll',
ADD_SUPPORT_TICKET: 'supportTicket/create',
GET_ALL_ROLES: 'userRole/getAllRole',
GET_ROLE_BY_ID: 'userRole/getRoleById',
ADD_ROLE: 'userRole/createrole',
GET_ALL_ORDER_COUNT: 'unitRepair/getOrderCountByStatus',
GET_ALL_ORDERS_IN_GRAPH: '/unitRepair/getOrdersByPeriod',
GET_USRE_BY_EMAIL: 'user/getUserByEmail',
GET_VIEW_VARIANT: 'variant/getAllVariantByModalNumberId/',



  AWS_IMAGE_BASE_URL:'https://userdocumentx.s3.ap-northeast-1.amazonaws.com/',
  // LOGIN: 'vendor/login
  CREATE_VENDOR:'vendor/createVendor',
  UPDATE_VENDOR_STATUS:'vendor/updateVendorAccountStatus',
  GET_ALL_VENDOR:'vendor/getAllVendor',

  GET_PROFILE:'User/getMyProfile',
CREATE_USER_BY_ADMIN: 'user/createUserByAdmin',
GET_ALL_USER: 'user/getAllUser',

  ADD_BRAND:'brand/addBrand',
  ADD_SUB_CATEGORY:'subCategory/addSubCategory',
  GET_ALL_SUB_CATEGORY_BY_ID:'subCategory/getallSubCategoriesByCategoryPK/',
  ADD_MODAL_NUMBER:'ProductModalNumber/addModalNumber',
  GET_ALL_MODAL_NUMBER:'ProductModalNumber/getAllModalNumber',
  GET_ALL_MODAL_NUMBER_BY_ID:'ProductModalNumber/getAllModalNumberByBrandPK/',
  GET_MODAL_NUMBER_BY_SC_ID: 'ProductModalNumber/getProductModelNumberBySubCategoryId',
  UPLOAD_SINGLE_IMAGE:'filUpload/profilePicture',
  UPLOAD_MODAL_IMAGES:'filUpload/uploadModalImages',
  ADD_VARIANT:'variant/addVariant',
  GET_ALL_VARIANT:'variant/getAllVariant',
  GET_ALL_VARIANT_BY_MODAL_NUMBER_ID:'variant/getAllVariantByModalNumberId/',
  ADD_PRODUCT:'product/addProduct',
  GET_ALL_VENDOR_PRODUCT_BY_VENDOR_ID:'vendorProduct/getAllVendorProductByVendorId',
  GET_ALL_VENDOR_PRODUCT:'product/getAllVendorProduct',
  GET_ALL_PRODUCT:'product/getAllVendorProduct',
  ADD_VENDOR_PRODUCT:'vendorProduct/addVendorProduct',
  UPDATE_VENDOR_PRODUCT:'/vendorProduct/updateStock/',
  ADD_COLOR:'color/addColor',
  GET_ALL_COLOR:'color/getAllColor',
  ADD_VARIANT_COLOR:'/modalColor/create',
  GET_ALL_VARIANT_COLOR:'/modalColor/getAllColor',


}

export {UrlConstants}